### ISSUE TITLE
Allow support for RHEL variants (and CentOS-like replacements) RockyLinux, AlmaLinux, and others

### ISSUE THREAD

**Issue by boldandbusted** [dockpack/ansible-vault#295] opened 2022-05-26 00:46 UTC
Thanks.

**Comment by boldandbusted** [comment] 2022-05-26 01:26
As a workaround, is there a way to 'force' the role to think that a RHEL variant is "CentOS"? Right now, unless you have the deprecated CentOS (or RHEL or Debian-variant), the role won't work. :/

**Comment by Mandorath** [comment] 2022-07-28 11:49
What I did to allow this to work for Rocky linux is:

Copy the RedHat8.yml file and name it Rocky.yml
 
Edit the main.yml file and add Rocky:

`
_vault_nix_distros:
  - 'Rocky'
  - 'RedHat'
  - 'CentOS'
`
After this it runs on Rocky assuming this should also work for Alma.

**Comment by mschuchard** [comment] 2022-09-27 20:32
@Mandorath Thanks for the fix. Could you put together a PR for the maintainers?

**Comment by gardar** [comment] 2022-10-06 23:25
This is fixed: https://github.com/ansible-community/ansible-vault/pull/309

Unfortunately I don't have permissions to close this issue and I saw it after the PR got merged so I couldn't tag it for closure there.

**Comment by mschuchard** [comment] 2022-10-07 10:41
@gardar If you write "closes #" or "fixes #"  in the PR body on GH, then the issue is closed automatically after PR merge. Thanks for the PR!

**Comment by gardar** [comment] 2022-10-07 12:33
> @gardar If you write "closes #" or "fixes #"  in the PR body on GH, then the issue is closed automatically after PR merge. Thanks for the PR!

Yeah I know, but I didn't think it would work if I'd add it to the PR description after it got merged.

**Closed as completed** 2023-02-28 09:36 UTC
